jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true
  # testing
#1
#on:
#pull_request:
#  branches:
#    - master
#  types: [closed]
#jobs: 
#  runpy:
#    if: github.event.pull_request.merged == true
#    steps: // the rest of the code

#2
#jobs:
#  - pipelineJob("DevopsJob"):
#      definition:
#        cpsScm:
#          scm:
#            git:
#              remote:
#                url: 'https://github.com/aviv321210/Aurora-Labs'
#              branch: '*/main'
#            scriptPath: 'jenkinsfile'
        
#3
jobs:
  - script: >
      pipelineJob('Devops is great') {
        definition {
          cpsScm {
            scm {
              git{
                remote{
                  url('https://github.com/aviv321210/Aurora-Labs')
                }
                branch('*/main')
              }
              scriptPath('Jenkinsfile')
            }
          }
        }
        triggers {
          githubPush()
        }
      }
     
  # end testing

security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy      
unclassified:
  location:
    url: http://localhost:8080/