FROM jenkins/jenkins:lts
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV CASC_JENKINS_CONFIG /var/jenkins_home/casc.yaml
COPY main.py /usr/share/jenkins/main.py
COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN jenkins-plugin-cli -f /usr/share/jenkins/plugins.txt
COPY casc.yaml /var/jenkins_home/casc.yaml
USER 0
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y python && rm -rf /var/lib/apt/lists/*