# docker-compose.yaml
version: '3.8'
services:
  jenkins:
    build: 
      context: .
      dockerfile: DockerFile
    image: docker.io/aviv321210/auroralabs:latest
    #privileged: true
    #user: root
    environment:
    - JENKINS_ADMIN_ID=admin
    - JENKINS_ADMIN_PASSWORD=password
    ports:
    - 8080:8080
    - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home: