FROM jenkins/jenkins:lts
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV CASC_JENKINS_CONFIG /var/jenkins_home/casc.yaml
COPY ./main.py /app
COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN jenkins-plugin-cli -f /usr/share/jenkins/plugins.txt
COPY casc.yaml /var/jenkins_home/casc.yaml
#RUN python install --production
#CMD ["python3", "app/main.py"]
#EXPOSE 8080