FROM jenkins/jenkins:lts
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV CASC_JENKINS_CONFIG /var/jenkins_home/casc.yaml
COPY main.py /usr/share/jenkins/main.py
COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN jenkins-plugin-cli -f /usr/share/jenkins/plugins.txt
COPY casc.yaml /var/jenkins_home/casc.yaml
USER 0
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y python && apt install -y openjdk-11-jdk-headless && rm -rf /var/lib/apt/lists/*
RUN keytool -genkey -keyalg RSA -alias selfsigned -dname "CN=Aviv Haviv, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown" -destkeystore /var/jenkins_home/jenkins_keystore.jks \
-storepass mypassword -keysize 2048;
ENV JENKINS_OPTS --httpsPort=8443 --httpsKeyStore="/var/jenkins_home/jenkins_keystore.jks" --httpsKeyStorePassword="mypassword"