# docker-compose.yaml
version: '3.8'
services:
  jenkins:
    build: 
      context: .
      dockerfile: DockerFile
    image: auroralabs:latest
    environment:
    - JENKINS_ADMIN_ID=admin
    - JENKINS_ADMIN_PASSWORD=password
    ports:
    - 443:8443
    - 8080:8080
    - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home: